services:
  - name: mcp-core
    env: docker
    repo: "https://github.com/troublestarter-dot/mcp-core"
    branch: feat/fastapi-mcp-skeleton
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: WEB_CONCURRENCY
        value: "2"
